services:
  - type: web
    name: sportv-credenciamento
    env: node
    plan: starter
    buildCommand: pnpm install --frozen-lockfile && vite build && esbuild server/_core/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: pnpm exec drizzle-kit push && pnpm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PNPM_VERSION
        value: 10.4.1
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: VITE_APP_ID
        sync: false
      - key: OAUTH_SERVER_URL
        sync: false
      - key: OWNER_OPEN_ID
        sync: false
      - key: BUILT_IN_FORGE_API_URL
        sync: false
      - key: BUILT_IN_FORGE_API_KEY
        sync: false
